# -*- coding: utf-8 -*-
"""Emit engine/assets/i18n.js for ToolTide from _i18n_tables.json.
Same architecture as the NeonPlay generator: single file, full dictionaries,
English baked into the HTML as the en fallback."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ORDER = ["zh", "es", "pt", "ru", "ja", "ko", "de", "fr", "id"]

with open(os.path.join(HERE, "_i18n_tables.json"), encoding="utf-8") as f:
    TABS = json.load(f)

HEADER = '''/* ToolTide i18n — site-wide runtime language switcher.
   Priority: ?lang= > localStorage(tt_lang) > navigator.language > en
   Wired regions: skip link, header search + nav, footer (brand/site links/
   category matrix/legal), homepage hero + search + category sections + value
   cards, show-all toggles, search-results strings, tool page section headers,
   about/privacy/contact/404. Per-tool unique prose (intro/howto/FAQ bodies,
   field labels) stays English in this tier. Generated by engine/_gen_i18n.py. */
(function(){
"use strict";
var LANGS=[
  {code:"en",   label:"English"},
  {code:"zh",   label:"简体中文"},
  {code:"es",   label:"Español"},
  {code:"pt",   label:"Português"},
  {code:"ru",   label:"Русский"},
  {code:"ja",   label:"日本語"},
  {code:"ko",   label:"한국어"},
  {code:"de",   label:"Deutsch"},
  {code:"fr",   label:"Français"},
  {code:"id",   label:"Bahasa Indonesia"}
];
var T={
'''

FOOTER = '''};
function detect(){
  var q=new URLSearchParams(location.search).get("lang");
  if(q&&LANGS.some(function(l){return l.code===q;}))return q;
  var s=null;try{s=localStorage.getItem("tt_lang");}catch(e){}
  if(s&&LANGS.some(function(l){return l.code===s;}))return s;
  var nl=(navigator.languages&&navigator.languages[0])||navigator.language||"en";
  var pref=function(p){return nl.indexOf(p)===0;};
  if(pref("zh"))return "zh";
  if(pref("es"))return "es";
  if(pref("pt"))return "pt";
  if(pref("ru"))return "ru";
  if(pref("ja"))return "ja";
  if(pref("ko"))return "ko";
  if(pref("de"))return "de";
  if(pref("fr"))return "fr";
  if(pref("id"))return "id";
  return "en";
}
var lang=detect();
window.ttLang=function(){return lang;};
window.ttSetLang=function(code){
  try{localStorage.setItem("tt_lang",code);}catch(e){}
  location.reload();
};
window.npT=function(key){
  var d=T[lang]||{};
  return Object.prototype.hasOwnProperty.call(d,key)?d[key]:null;
};
function subst(el,v){
  v=v.replace(/\\{year\\}/g,String(new Date().getFullYear()));
  return v;
}
function apply(){
  var nodes=document.querySelectorAll("[data-i18n]");
  for(var i=0;i<nodes.length;i++){
    var el=nodes[i],v=npT(el.getAttribute("data-i18n"));
    if(v==null)continue;
    v=subst(el,v);
    if(el.hasAttribute("data-i18n-html"))el.innerHTML=v;
    else if(el.children.length===0)el.textContent=v;
  }
  ["placeholder","aria-label","title"].forEach(function(at){
    var ns=document.querySelectorAll("[data-i18n-"+at+"]");
    for(var j=0;j<ns.length;j++){
      var t=npT(ns[j].getAttribute("data-i18n-"+at));
      if(t!=null)ns[j].setAttribute(at,t);
    }
  });
}
window.npApply=apply;
function switcher(){
  var row=document.querySelector(".site-head .nav-row");
  if(!row)return;
  var b=document.createElement("button");
  b.id="lang-btn";b.textContent="🌐 "+lang.toUpperCase();
  b.setAttribute("aria-label","Language");
  b.style.cssText="background:transparent;border:1px solid rgba(148,163,184,.45);color:inherit;border-radius:8px;padding:4px 8px;font-size:.8rem;cursor:pointer;margin-left:6px";
  var dd=document.createElement("div");
  dd.style.cssText="position:absolute;right:0;top:110%;background:#fff;border:1px solid #cbd5e1;border-radius:10px;padding:6px;display:none;flex-direction:column;min-width:150px;z-index:60;box-shadow:0 8px 24px rgba(15,23,42,.18)";
  if(document.documentElement.getAttribute("data-theme")==="dark"){
    dd.style.background="#1e293b";dd.style.borderColor="#334155";
  }
  LANGS.forEach(function(l){
    var o=document.createElement("div");
    o.textContent=l.label;
    o.style.cssText="padding:7px 12px;border-radius:6px;cursor:pointer;font-size:.9rem;white-space:nowrap"+(l.code===lang?";color:#0e7490;font-weight:600":"");
    o.addEventListener("click",function(e){e.stopPropagation();window.ttSetLang(l.code);});
    o.addEventListener("mouseenter",function(){o.style.background="#f1f5f9";});
    o.addEventListener("mouseleave",function(){o.style.background="transparent";});
    dd.appendChild(o);
  });
  var wrap=document.createElement("div");
  wrap.style.cssText="position:relative;display:inline-block";
  wrap.appendChild(b);wrap.appendChild(dd);
  b.addEventListener("click",function(e){e.stopPropagation();dd.style.display=dd.style.display==="flex"?"none":"flex";});
  document.addEventListener("click",function(){dd.style.display="none";});
  row.appendChild(wrap);
}
function boot(){
  apply();
  switcher();
  document.documentElement.lang=lang;
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);
else boot();
})();'''


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


parts = [HEADER]
for li, lang in enumerate(ORDER):
    entries = [tuple(x) for x in TABS["chrome"][lang]]
    parts.append(lang + ":{\n")
    for ki, (k, v) in enumerate(entries):
        comma = "," if ki < len(entries) - 1 else ""
        parts.append(' "%s":"%s"%s\n' % (k, esc(v), comma))
    parts.append("}" + ("," if li < len(ORDER) - 1 else "") + "\n")
parts.append(FOOTER)
out = "".join(parts)
with open(os.path.join(HERE, "assets", "i18n.js"), "w", encoding="utf-8", newline="\n") as f:
    f.write(out)
print("written", len(out), "chars,", len(TABS["chrome"]["zh"]), "keys/lang")
